### ISSUE TITLE
Add reference to dapp sample for wallet to https://hub.doc.eluv.io/mediawallet/developer/

### ISSUE THREAD

**Issue by elv-michelle** [eluv-io/elv-docs#6]
Re my slack comment, please add this [](https://dapp-sample.app.eluv.io/ ) to the media wallet section here [](https://hub.doc.eluv.io/mediawallet/developer/)

My thought is that it should appear in this section as it is a complete application sample, after the login sample ....  But add where you like.

_Using Eluvio Wallet Client
Using the Eluvio Wallet Client, you can use the [LogIn](https://eluv-io.github.io/elv-client-js/wallet-client/ElvWalletClient.html#LogIn) method. This will redirect your application to the Eluvio Media Wallet, where the user will log in with the standard Media Wallet login flow (using either the custodial wallet or MetaMask), and redirect back with a signed token that your client will use to perform actions on behalf of the user.

Using the Eluvio Wallet Frame Client
If you’ve embedded the Eluvio Media Wallet into your site with the frame client, there are two options for dealing with login.

The simplest option is to just allow the Eluvio Media Wallet application handle login natively. If the frame is visible, the user can simply navigate through the login flow with the standard Media Wallet UI. The frame client also offers a [LogIn](https://eluv-io.github.io/elv-media-wallet/ElvWalletFrameClient.html#LogIn) method that you can use in your application, but please note that this often runs afoul of popup blockers, as login via the embedded media wallet uses a popup and browsers require a deliberate user action in the frame to generate a popup without being blocked. It is recommended to use the method below instead.

The other option is to use the full Eluvio Wallet Client login flow (see above), retrieve the token, then pass that token to the embedded wallet via the frame client. This is recommended if you are using both clients, as the frame client cannot access the auth token from the embedded application, so if the user logs in via the frame client, you cannot set up the full wallet client to use that authentication.

Using both clients can be useful if you want to implement your own login screen separate from the Media Wallet application, or if you need to access wallet functionality on pages where the wallet application is not embedded.

To see code examples of all three options, see [this example](https://github.com/eluv-io/elv-media-wallet/blob/main/test/login.js)._

And in the Resources links at the bottom of the page.

**Comment by elv-todd** [comment]
fixed by:
- https://github.com/qluvio/hub/pull/28
- https://github.com/qluvio/hub/pull/29
